services:
  db:
    image: postgres:17
    container_name: project-eyo_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tabletrack
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: tabletrack_server
    depends_on:
      - db
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/tabletrack
    command: sh -c "/wait-for-it.sh db:5432 -- pnpm db:generate && pnpm db:migrate && pnpm start:dev"



  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: tabletrack_client
    depends_on:
      - server
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001

volumes:
  db_data:
