services:
  db:
    image: postgres:17
    container_name: tabletrack_db
    restart: always
    env_file:
      - ./server/.env.docker
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: tabletrack_server
    depends_on:
      - db
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env.docker
    command: >
      sh -c "/wait-for-it.sh db:5432 -t 5 -- pnpm db:generate && pnpm db:migrate &&pnpm start:dev"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: tabletrack_client
    depends_on:
      - server
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - ./client/.env.docker
    

volumes:
  db_data:
